apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dapr-services
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      dapr.io/enabled: "true"
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
